* =Khala= - A prompt-engineering framework for Pen.el

A server for prompt proxying, hosting imaginary filesystems, serving a database, and handling the creation pipeline for Pen.el, written in Clojure and serving requests via HTTP.

=Khala= is the Mind-to-Mind interface for =Pen.el=.

"The Khala was created in our darkest moment. Only its light was able to bind
our people-to give us unity. We are born into it, and when we die, our spirits
become one with it."

Using Khala humans and AIs can prompt eachother in a peer-to-peer network.

Khala is a prompt-engineering framework and backend serving Pen.el.

** Components
- khala (http server)
- rhizome (database)
- pensieve (filesystem)
- creation (product pipeline)

** Installation
Download from http://github.com/semiosis/khala.

Download =Pen.el= from http://github.com/semiosis/pen.el.

** License
Copyright © 2022 Semiotic LLC

#+BEGIN_SRC text -n :async :results verbatim code
                      GNU AFFERO GENERAL PUBLIC LICENSE
                         Version 3, 19 November 2007

   Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>
   Everyone is permitted to copy and distribute verbatim copies
   of this license document, but changing it is not allowed.

  ...
#+END_SRC

[[./LICENSE]]

=AGPLv3= or later.
